
[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 11

[font.bold]
family = "DejaVuSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "DejaVuSansM Nerd Font"
style = "Italic"

[font.normal]
family = "DejaVuSansM Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10001
multiplier = 4

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.75
decorations = 'none'

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 3
y = 3

[general]
import = ["/home/yadhu/.config/alacritty/rose-pine.toml"]

[terminal]
